setwd("C:/Giulio/Data Science/Johns Hopkins/Curso 3 - Getting and Cleaning data/Week 4/Assigment")
if(!file.exists("Downloaded Data")){
        dir.create("Downloaded Data")
}
fileUrl <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
download.file(fileUrl, destfile = "C:\\Giulio\\Data Science\\Johns Hopkins\\Curso 3 - Getting and Cleaning data\\Week 4\\Assigment\\Downloaded Data\\UCI HAR Dataset.zip")
setwd("C:/Giulio/Data Science/Johns Hopkins/Curso 3 - Getting and Cleaning data/Week 4/Assigment/Downloaded Data")
unzip(zipfile = "UCI HAR Dataset.zip")
ActivityTest  <- read.table("UCI HAR Dataset/test/y_test.txt")
ActivityTrain <- read.table("UCI HAR Dataset/train/y_train.txt")
SubjectTrain <- read.table("UCI HAR Dataset/train/subject_train.txt")
SubjectTest  <- read.table("UCI HAR Dataset/test/subject_test.txt")
DataTest  <- read.table("UCI HAR Dataset/test/X_test.txt" )
DataTrain <- read.table("UCI HAR Dataset/train/X_train.txt")
ActivityLabels<-read.table("UCI HAR Dataset/activity_labels.txt")
FeatureNames<-read.table("UCI HAR Dataset/features.txt")
DataActivity<-rbind(ActivityTest,ActivityTrain)
DataSubject<-rbind(SubjectTest,SubjectTrain)
Data<-rbind(DataTest,DataTrain)
library(dplyr)
DataActivity<-merge(DataActivity,ActivityLabels,"V1")
DataActivity<- rename(DataActivity, Activity = V2)
DataActivity<-select(DataActivity, Activity)
DataSubject<-rename(DataSubject, Subject = V1)
DataColNames<-as.character(FeatureNames$V2)
Data<-`colnames<-`(Data,DataColNames)
DataSubAct<-cbind(DataSubject,DataActivity)
DataTotal<-cbind(DataSubAct,Data)
SelectedCol<-as.character(FeatureNames$V2[grep("mean\\(\\)|std\\(\\)",FeatureNames$V2)])
DataTotalSub<-DataTotal[c("Activity","Subject",SelectedCol)]
TidyData<-aggregate(. ~Subject + Activity, DataTotalSub, mean)
TidyData<-arrange(TidyData, Subject, Activity)
View(DataTotalSub)
View(TidyData)
write.table(TidyData, file = "tidydata.txt",row.name=FALSE)